### ISSUE TITLE
no visible @interface

### ISSUE THREAD

**Issue by sdnorm** [doefler/react-native-social-share#19]
I keep getting `No visible @interface for 'RCTRootView' declares the selector 'initWithBundleURL:moduleName:launchOptions:'`

I have reinstalled the library and started a new project to test it. The error message comes up when I go to click on an action like "tweet". 

`"dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-native-social-share": "^0.7.0"
  }`

**Comment by doefler** [comment]
Hi @sdnorm 

As it is very long time since I made this repo, I don't really know too much about any changes that have been made to react native.

I tried to do a clean install of react native on my computer and installed react-native-social-share. I followed the instructions in the readme and did some tweaking to the example js code to follow the new syntax (ES6 or ES7 i guess).

I works on my computer, both Facebook and Twitter sharing.

Can you walk my trough how you started your new project, maybe I can see something that could be done differently 👍

**Comment by sdnorm** [comment]
To test it again I did the following: 

`react-native init social` -> then followed the instructions you have. 

I am still getting the same error. Not sure what is happening. I am just going to use the [react-native-share](https://github.com/EstebanFuentealba/react-native-share) package to finish my app. On my next app I will try this package again, I liked it when I had it working.
