### ISSUE TITLE
Cannot read property 'tweet' of undefined

### ISSUE THREAD

**Issue by kenvandemar** [doefler/react-native-social-share#38]
Hi Kim,
I am using your repo for my project. 
I've implemented exactly what you instruction in README file ( the new one), 
but when I click Tweet button, it raised the error 'Cannot read Property 'tweet' of undefined.

Can you help me to resolve it?

**Comment by kenvandemar** [comment]
I figured it out! I need to import 2 libs inside my XCode

**Comment by dwilt** [comment]
@kenvandemar can you close?

**Comment by dwilt** [comment]
@kenvandemar I'm unable to get this to work and running into what seems like the same issue as https://github.com/doefler/react-native-social-share/issues/38. What libs did you import? Can you provide some more instructions on how you solved it?

**Comment by doefler** [comment]
@dwilt 
Check the old installation guide out in this version of the Readme
https://github.com/doefler/react-native-social-share/commit/16def726914c5c47ecdccbe648f6e92c128d5aec

**Comment by doefler** [comment]
1. `npm install react-native-social-share --save`
2. In XCode, in the project navigator right click `Libraries` ➜ `Add Files to [your project's name]`
3. Go to `node_modules` ➜ `react-native-social-share`➜ iOS and add `KDSocialShare.h` and `KDSocialShare.m` 
4. Go to your project's `Build Phases` ➜ `Link Binary With Libraries` phase
5. Add `Social.framework` to ➜ `Link Binary With Libraries` build phase of your project (click the '+' and search for 'social').
6. Run your project (`Cmd+R`)

**Comment by doefler** [comment]
I will change the readme back to the old guide now

**Comment by dwilt** [comment]
@doefler thanks! yep, those instructions worked.

**Comment by fendorio** [comment]
For any android guys out there, I ran into the same problem this morning, I usually build straight from the CLI, e.g. 

    react-native start 

However, this was not working, as the KDSocialShare module was not included in the build, thus is was undefined, and of course this is the object 'tweet' is a property of, hence the error. 

I needed to recompile the binary, which worked straight away after I had done it. 

    react-native run android 

Presto, it worked(s)

**Comment by doefler** [comment]
Hey @fendorio 
Thanks for sharing 😄 
I am not sure what the second code snippet you shared did:
```BASH
react-native run android 
```
Did that "recompile the binary" or just run the code?

Do you think we should add this to the readme file?

**Comment by fendorio** [comment]
Hey @doefler 

No problem! 

It rebuilds/recompiles the android version of the App, and runs it automatically afterwards either on a connected device, or on an emulator (I think, I always use device, not emulator) after the app has finished building. 

This is actually a common issue with adding custom fonts to react native on android, lots of people add fonts, link them so that they're present in the /android directory, and report it's broken because the fonts don't show (font families aren't being found at runtime),  running react-native run android fixes this issue also, i'm guessing for the same reason, i.e. the files aren't actually getting compiled into the binary file when running with 'react-native start'. 

Definitely think it should go into the readme, this is definitely a missing step on android. 

Essentially it's all down to this line:

Line 5 of react-native-social-share.js

    var KDSocialShare = require('react-native').NativeModules.KDSocialShare;

This is undefined, after running (tested with npm AND yarn, although that would make no difference anyway...):

    npm install && react-native link

    console.log( KDSocialShare === undefined) // Logs true (placed on line 6 of the script)

After running the commands above, and the command in question (below)

    react-native run android 

    console.log(KDSocialShare === undefined) // Logs false (placed on line 6 of the script)

Everything works :)
